config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  get "/sales" => "sales#index", as: "sales_index"
  get "/sales/report" => "sales#report", as: "sales_report"

  resources :sales



  resources :vds
  resources :products



  get 'info/infogem'

  get 'info/infoauthor'

  get 'info/infolatestgems'

  get 'welcomesp/index'

  resources :dependencies
  get 'sessions/create'

  get 'welcome/index'

  resources :locations


  #root 'welcome#index'

#shuaib api
  #root 'welcomesp#index'
  match 'searchgem', to: 'info#infogem', via: [:get, :post]



  #viak product
  resources :products

  root 'products#index'

  mount Products::ProductsAPI => '/api/products'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
match 'auth/failure', to:  redirect("/") , via: [:get, :post]
match 'signout', to: 'sessions#signout', via: [:get, :post]
match 'twittertrends', to: 'welcome#twittertrends', via: [:get, :post]
match 'customtweets', to: 'welcome#customtweets', via: [:get]
match 'morecustomtweets', to: 'welcome#morecustomtweets', via: [:get]
end

app/models/api_key.rb
class ApiKey < ApplicationRecord
	before_create :generate_access_token

private 
	def generate_access_token
		begin
			self.access_token = SecureRandom.hex
		end while self.class.exists?(access_token: access_token)
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dependency.rb
class Dependency < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
	geocoded_by :address      
  after_validation :geocode  
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, presence: true
  validates :price, presence: true
  validates :short_description, presence: true
end

app/models/rubygemsorg.rb
class RubyGemsOrg
include HTTParty
# GET - /api/v1/gems/[GEM NAME].(json|xml|yaml)
def self.getGemInfo(name)
url="https://rubygems.org/api/v1/gems/#{name}.json"
response = HTTParty.get(url)
responsebody = JSON.parse(response.body)
return responsebody
end
# GET - /api/v1/owners/[USER HANDLE]/gems.(json|xml|yaml)
def self.getGemsOfAuthor(name)
url="https://rubygems.org/api/v1/owners/#{name}/gems.json"
response = HTTParty.get(url)
responsebody = JSON.parse(response.body)
return responsebody
end

end

app/models/sale.rb
class Sale < ApplicationRecord
end

app/models/user.rb
class User < ActiveRecord::Base
def self.create_from_omniauth(auth)
create! do |user|
user.provider = auth["provider"]
user.userid = auth["uid"]
user.name = auth["info"]["nickname"]
end
end
end

app/models/vd.rb
class Vd < ApplicationRecord
end

app/controllers/dependencies_controller.rb
class DependenciesController < ApplicationController
  before_action :set_dependency, only: [:show, :edit, :update, :destroy]

  # GET /dependencies
  # GET /dependencies.json
  def index
    @dependencies = Dependency.all
  end

  # GET /dependencies/1
  # GET /dependencies/1.json
  def show
  end

  # GET /dependencies/new
  def new
    @dependency = Dependency.new
  end

  # GET /dependencies/1/edit
  def edit
  end

  # POST /dependencies
  # POST /dependencies.json
  def create
    @dependency = Dependency.new(dependency_params)

    respond_to do |format|
      if @dependency.save
        format.html { redirect_to @dependency, notice: 'Dependency was successfully created.' }
        format.json { render :show, status: :created, location: @dependency }
      else
        format.html { render :new }
        format.json { render json: @dependency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dependencies/1
  # PATCH/PUT /dependencies/1.json
  def update
    respond_to do |format|
      if @dependency.update(dependency_params)
        format.html { redirect_to @dependency, notice: 'Dependency was successfully updated.' }
        format.json { render :show, status: :ok, location: @dependency }
      else
        format.html { render :edit }
        format.json { render json: @dependency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dependencies/1
  # DELETE /dependencies/1.json
  def destroy
    @dependency.destroy
    respond_to do |format|
      format.html { redirect_to dependencies_url, notice: 'Dependency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dependency
      @dependency = Dependency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dependency_params
      params.require(:dependency).permit(:name, :authors, :version)
    end
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
require 'rubygemsorg'

  def infogem
  	if params[:search_gem].to_s.present?
name = params[:search_gem]
response = RubyGemsOrg.getGemInfo(name)
name = response['name']
@dependency = Dependency.find_by(:name => name)
if @dependency.blank?
@dependency = Dependency.create(:name=>response['name'],
:authors=>response['authors'],:version=>response['version'])
end
else
redirect_to(root_url)
end
end

  

  def infoauthor
  	if params[:search_author].to_s.present?
@author= params[:search_author]
@response = RubyGemsOrg.getGemsOfAuthor(@author)
else
redirect_to(root_url)
end
end


  def infolatestgems
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

  def index
  end

  def report
    ReportWorker.perform_async("07-01-2016", "08-01-2016")
    render text: "REQUEST ADDED TO QUEUE"
  end

  private
  def generate_report
    sleep 30
  end

end

app/controllers/vds_controller.rb
class VdsController < ApplicationController
  before_action :set_vd, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "admin", password: "admin"
 before_filter :restrict_access
  # GET /vds
  # GET /vds.json
  def index
    @vds = Vd.all
  end

  # GET /vds/1
  # GET /vds/1.json
  def show
  end

  # GET /vds/new
  def new
    @vd = Vd.new
  end

  # GET /vds/1/edit
  def edit
  end

  # POST /vds
  # POST /vds.json
  def create
    @vd = Vd.new(vd_params)

    respond_to do |format|
      if @vd.save
        format.html { redirect_to @vd, notice: 'Vd was successfully created.' }
        format.json { render :show, status: :created, location: @vd }
      else
        format.html { render :new }
        format.json { render json: @vd.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vds/1
  # PATCH/PUT /vds/1.json
  def update
    respond_to do |format|
      if @vd.update(vd_params)
        format.html { redirect_to @vd, notice: 'Vd was successfully updated.' }
        format.json { render :show, status: :ok, location: @vd }
      else
        format.html { render :edit }
        format.json { render json: @vd.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vds/1
  # DELETE /vds/1.json
  def destroy
    @vd.destroy
    respond_to do |format|
      format.html { redirect_to vds_url, notice: 'Vd was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vd
      @vd = Vd.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vd_params
      params.require(:vd).permit(:name, :email)
    end

    private
      def restrict_access
        api_key = ApiKey.find_by_access_token(params[:access_token])
        head :unauthorized unless api_key
      end
    end
    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dependencies_helper.rb
module DependenciesHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/vds_helper.rb
module VdsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/welcomesp_helper.rb
module WelcomespHelper
end

app/views/dependencies/_form.html.erb
<%= form_for(dependency) do |f| %>
  <% if dependency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dependency.errors.count, "error") %> prohibited this dependency from being saved:</h2>

      <ul>
      <% dependency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :authors %>
    <%= f.text_field :authors %>
  </div>

  <div class="field">
    <%= f.label :version %>
    <%= f.text_field :version %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dependencies/edit.html.erb
<h1>Editing Dependency</h1>

<%= render 'form', dependency: @dependency %>

<%= link_to 'Show', @dependency %> |
<%= link_to 'Back', dependencies_path %>

app/views/dependencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dependencies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Authors</th>
      <th>Version</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dependencies.each do |dependency| %>
      <tr>
        <td><%= dependency.name %></td>
        <td><%= dependency.authors %></td>
        <td><%= dependency.version %></td>
        <td><%= link_to 'Show', dependency %></td>
        <td><%= link_to 'Edit', edit_dependency_path(dependency) %></td>
        <td><%= link_to 'Destroy', dependency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dependency', new_dependency_path %>

app/views/dependencies/new.html.erb
<h1>New Dependency</h1>

<%= render 'form', dependency: @dependency %>

<%= link_to 'Back', dependencies_path %>

app/views/dependencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dependency.name %>
</p>

<p>
  <strong>Authors:</strong>
  <%= @dependency.authors %>
</p>

<p>
  <strong>Version:</strong>
  <%= @dependency.version %>
</p>

<%= link_to 'Edit', edit_dependency_path(@dependency) %> |
<%= link_to 'Back', dependencies_path %>