config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  get "/sales" => "sales#index", as: "sales_index"
  get "/sales/report" => "sales#report", as: "sales_report"

  resources :sales



  resources :vds
  resources :products



  get 'info/infogem'

  get 'info/infoauthor'

  get 'info/infolatestgems'

  get 'welcomesp/index'

  resources :dependencies
  get 'sessions/create'

  get 'welcome/index'

  resources :locations


  #root 'welcome#index'

#shuaib api
  #root 'welcomesp#index'
  match 'searchgem', to: 'info#infogem', via: [:get, :post]



  #viak product
  resources :products

  root 'products#index'

  mount Products::ProductsAPI => '/api/products'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
match 'auth/failure', to:  redirect("/") , via: [:get, :post]
match 'signout', to: 'sessions#signout', via: [:get, :post]
match 'twittertrends', to: 'welcome#twittertrends', via: [:get, :post]
match 'customtweets', to: 'welcome#customtweets', via: [:get]
match 'morecustomtweets', to: 'welcome#morecustomtweets', via: [:get]
end

app/models/api_key.rb
class ApiKey < ApplicationRecord
	before_create :generate_access_token

private 
	def generate_access_token
		begin
			self.access_token = SecureRandom.hex
		end while self.class.exists?(access_token: access_token)
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dependency.rb
class Dependency < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
	geocoded_by :address      
  after_validation :geocode  
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, presence: true
  validates :price, presence: true
  validates :short_description, presence: true
end

app/models/rubygemsorg.rb
class RubyGemsOrg
include HTTParty
# GET - /api/v1/gems/[GEM NAME].(json|xml|yaml)
def self.getGemInfo(name)
url="https://rubygems.org/api/v1/gems/#{name}.json"
response = HTTParty.get(url)
responsebody = JSON.parse(response.body)
return responsebody
end
# GET - /api/v1/owners/[USER HANDLE]/gems.(json|xml|yaml)
def self.getGemsOfAuthor(name)
url="https://rubygems.org/api/v1/owners/#{name}/gems.json"
response = HTTParty.get(url)
responsebody = JSON.parse(response.body)
return responsebody
end

end

app/models/sale.rb
class Sale < ApplicationRecord
end

app/models/user.rb
class User < ActiveRecord::Base
def self.create_from_omniauth(auth)
create! do |user|
user.provider = auth["provider"]
user.userid = auth["uid"]
user.name = auth["info"]["nickname"]
end
end
end

app/models/vd.rb
class Vd < ApplicationRecord
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
require 'rubygemsorg'

  def infogem
  	if params[:search_gem].to_s.present?
name = params[:search_gem]
response = RubyGemsOrg.getGemInfo(name)
name = response['name']
@dependency = Dependency.find_by(:name => name)
if @dependency.blank?
@dependency = Dependency.create(:name=>response['name'],
:authors=>response['authors'],:version=>response['version'])
end
else
redirect_to(root_url)
end
end

  

  def infoauthor
  	if params[:search_author].to_s.present?
@author= params[:search_author]
@response = RubyGemsOrg.getGemsOfAuthor(@author)
else
redirect_to(root_url)
end
end


  def infolatestgems
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = 'Product added!'
      redirect_to root_path
    else
      flash[:error] = 'Failed to edit product!'
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      flash[:notice] = 'Product updated!'
      redirect_to root_path
    else
      flash[:error] = 'Failed to edit product!'
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.delete
      flash[:notice] = 'Product deleted!'
      redirect_to root_path
    else
      flash[:error] = 'Failed to delete this product!'
      render :destroy
    end
  end

  def product_params
    params.require(:product).permit(:name, :price, :old_price, :short_description, :full_description)
  end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

  def index
  end

  def report
    ReportWorker.perform_async("07-01-2016", "08-01-2016")
    render text: "REQUEST ADDED TO QUEUE"
  end

  private
  def generate_report
    sleep 30
  end

end

app/controllers/vds_controller.rb
class VdsController < ApplicationController
  before_action :set_vd, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "admin", password: "admin"
 before_filter :restrict_access
  # GET /vds
  # GET /vds.json
  def index
    @vds = Vd.all
  end

  # GET /vds/1
  # GET /vds/1.json
  def show
  end

  # GET /vds/new
  def new
    @vd = Vd.new
  end

  # GET /vds/1/edit
  def edit
  end

  # POST /vds
  # POST /vds.json
  def create
    @vd = Vd.new(vd_params)

    respond_to do |format|
      if @vd.save
        format.html { redirect_to @vd, notice: 'Vd was successfully created.' }
        format.json { render :show, status: :created, location: @vd }
      else
        format.html { render :new }
        format.json { render json: @vd.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vds/1
  # PATCH/PUT /vds/1.json
  def update
    respond_to do |format|
      if @vd.update(vd_params)
        format.html { redirect_to @vd, notice: 'Vd was successfully updated.' }
        format.json { render :show, status: :ok, location: @vd }
      else
        format.html { render :edit }
        format.json { render json: @vd.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vds/1
  # DELETE /vds/1.json
  def destroy
    @vd.destroy
    respond_to do |format|
      format.html { redirect_to vds_url, notice: 'Vd was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vd
      @vd = Vd.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vd_params
      params.require(:vd).permit(:name, :email)
    end

    private
      def restrict_access
        api_key = ApiKey.find_by_access_token(params[:access_token])
        head :unauthorized unless api_key
      end
    end
    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dependencies_helper.rb
module DependenciesHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/vds_helper.rb
module VdsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/welcomesp_helper.rb
module WelcomespHelper
end

app/views/products/delete.html.erb
<h1>Products#delete</h1>
<p>Find me in app/views/products/delete.html.erb</p>

app/views/products/edit.html.erb
<div class="modal-content">
  <%= form_for @product, url: {action: :update} do |f| %>
      <div class="modal-header">
        <h4 class="modal-title">Add a Product</h4>
      </div>
      <div class="modal-body">
        <p>
          <%= "<div class=\"alert alert-danger\">#{@product.errors.full_messages.first}</div>".html_safe if @product.errors.any? %>
        <div class="form-group">
          <div class="row">
            <div class="col-xs-8">
              <label class="control-label">Product Name</label>
              <%= f.text_field :name, :class => "form-control" %>
            </div>

            <div class="col-xs-4">
              <label class="control-label">Price</label>
              <%= f.text_field :price, :class => "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-xs-12">
              <label class="control-label">Short Description</label>
              <%= f.text_field :short_description, :class => "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-xs-12">
              <label class="control-label">Full Description</label>
              <%= f.text_area :full_description, :rows => 5, :class => "form-control" %>
            </div>
          </div>
        </div>

        </p>
      </div>
      <div class="modal-footer">
        <%= link_to 'Back', { controller: 'products', action: 'index'}, class: 'btn btn-default'%>
        <%= f.submit 'Update Product', :class => "btn btn-primary" %>
      </div>
  <% end %>
</div>

app/views/products/index.html.erb
<H1>Welcome to Ruby application consuming APIs</h1>

<div class="modal-content">
  <div class="modal-header">
    <h4 class="modal-title">Products</h4>
  </div>
  <div class="modal-body">
    <p>
      <div class="btn-group">
        <%= link_to 'Add Product', new_product_path, class: 'btn btn-success'%>
      </div>
    </p>
    <table id="products" class="display" cellspacing="0" width="100%">
      <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Short Description</th>
        <th>Full Description</th>
        <th>Last Modified</th>
        <th>Date Added</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tfoot>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Short Description</th>
        <th>Full Description</th>
        <th>Last Modified</th>
        <th>Date Added</th>
        <th>Actions</th>
      </tr>
      </tfoot>
      <tbody>
      <% @products.each do |product| %>
          <tr>
            <td><%= product.name %></td>
            <td>RON <%= product.price %></td>
            <td><%= truncate(product.short_description, :length => 75) %></td>
            <td><%= truncate(product.full_description, :length => 150) %></td>
            <td><%= product.updated_at %></td>
            <td><%= product.created_at %></td>
            <td>
              <div class="btn-group">
                <%= link_to 'Show', product_path(product), class: 'btn btn-primary' %>
                <%= link_to 'Edit', edit_product_path(product), class: 'btn btn-success' %>
                <%= link_to 'Delete', product_path(product), method: :delete, class: 'btn btn-danger' %>
              </div>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>


<H4>Click Below to Find Ruby Gems</h4>
<%= form_tag('searchgem', method: 'post') do %>
<%= label_tag(:search_gem, 'Search for gem:') %>
<%= text_field_tag(:search_gem) %>
<%= submit_tag('Search gem') %>
<% end %>

<h3><%= link_to 'Click to Find Location', new_location_path, class: 'btn btn-success'%></h3>

app/views/products/new.html.erb
<div class="modal-content">
  <%= form_for @product, url: {action: :create} do |f| %>
      <div class="modal-header">
        <h4 class="modal-title">Add a Product</h4>
      </div>
      <div class="modal-body">
        <p>
          <%= "<div class=\"alert alert-danger\">#{@product.errors.full_messages.first}</div>".html_safe if @product.errors.any? %>
        <div class="form-group">
          <div class="row">
            <div class="col-xs-8">
              <label class="control-label">Product Name</label>
              <%= f.text_field :name, :class => "form-control" %>
            </div>

            <div class="col-xs-4">
              <label class="control-label">Price</label>
              <%= f.text_field :price, :class => "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-xs-12">
              <label class="control-label">Short Description</label>
              <%= f.text_field :short_description, :class => "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-xs-12">
              <label class="control-label">Full Description</label>
              <%= f.text_area :full_description, :rows => 5, :class => "form-control" %>
            </div>
          </div>
        </div>

        </p>
      </div>
      <div class="modal-footer">
        <%= link_to 'Back', { controller: 'products', action: 'index'}, class: 'btn btn-default'%>
        <%= f.submit 'Create Product', :class => "btn btn-primary" %>
      </div>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Add a Product</h4>
      </div>
      <div class="modal-body">
        <p>
        <div class="form-group">
          <div class="row">
            <div class="col-xs-8">
              <label class="control-label">Product Name</label>
              <%= @product.name %>
            </div>

            <div class="col-xs-4">
              <label class="control-label">Price</label>
              <%= @product.price %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-xs-12">
              <label class="control-label">Short Description</label>
              <%= @product.short_description %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-xs-12">
              <label class="control-label">Full Description</label>
              <%= @product.full_description %>
            </div>
          </div>
        </div>

        </p>
      </div>
      <div class="modal-footer">
        <%= link_to 'Back', { controller: 'products', action: 'index'}, class: 'btn btn-default'%>
      </div>
</div>