config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  get "/sales" => "sales#index", as: "sales_index"
  get "/sales/report" => "sales#report", as: "sales_report"

  resources :sales



  resources :vds
  resources :products



  get 'info/infogem'

  get 'info/infoauthor'

  get 'info/infolatestgems'

  get 'welcomesp/index'

  resources :dependencies
  get 'sessions/create'

  get 'welcome/index'

  resources :locations


  #root 'welcome#index'

#shuaib api
  #root 'welcomesp#index'
  match 'searchgem', to: 'info#infogem', via: [:get, :post]



  #viak product
  resources :products

  root 'products#index'

  mount Products::ProductsAPI => '/api/products'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
match 'auth/failure', to:  redirect("/") , via: [:get, :post]
match 'signout', to: 'sessions#signout', via: [:get, :post]
match 'twittertrends', to: 'welcome#twittertrends', via: [:get, :post]
match 'customtweets', to: 'welcome#customtweets', via: [:get]
match 'morecustomtweets', to: 'welcome#morecustomtweets', via: [:get]
end

app/models/api_key.rb
class ApiKey < ApplicationRecord
	before_create :generate_access_token

private 
	def generate_access_token
		begin
			self.access_token = SecureRandom.hex
		end while self.class.exists?(access_token: access_token)
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dependency.rb
class Dependency < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
	geocoded_by :address      
  after_validation :geocode  
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, presence: true
  validates :price, presence: true
  validates :short_description, presence: true
end

app/models/rubygemsorg.rb
class RubyGemsOrg
include HTTParty
# GET - /api/v1/gems/[GEM NAME].(json|xml|yaml)
def self.getGemInfo(name)
url="https://rubygems.org/api/v1/gems/#{name}.json"
response = HTTParty.get(url)
responsebody = JSON.parse(response.body)
return responsebody
end
# GET - /api/v1/owners/[USER HANDLE]/gems.(json|xml|yaml)
def self.getGemsOfAuthor(name)
url="https://rubygems.org/api/v1/owners/#{name}/gems.json"
response = HTTParty.get(url)
responsebody = JSON.parse(response.body)
return responsebody
end

end

app/models/sale.rb
class Sale < ApplicationRecord
end

app/models/user.rb
class User < ActiveRecord::Base
def self.create_from_omniauth(auth)
create! do |user|
user.provider = auth["provider"]
user.userid = auth["uid"]
user.name = auth["info"]["nickname"]
end
end
end

app/models/vd.rb
class Vd < ApplicationRecord
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
require 'rubygemsorg'

  def infogem
  	if params[:search_gem].to_s.present?
name = params[:search_gem]
response = RubyGemsOrg.getGemInfo(name)
name = response['name']
@dependency = Dependency.find_by(:name => name)
if @dependency.blank?
@dependency = Dependency.create(:name=>response['name'],
:authors=>response['authors'],:version=>response['version'])
end
else
redirect_to(root_url)
end
end

  

  def infoauthor
  	if params[:search_author].to_s.present?
@author= params[:search_author]
@response = RubyGemsOrg.getGemsOfAuthor(@author)
else
redirect_to(root_url)
end
end


  def infolatestgems
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

  def index
  end

  def report
    ReportWorker.perform_async("07-01-2016", "08-01-2016")
    render text: "REQUEST ADDED TO QUEUE"
  end

  private
  def generate_report
    sleep 30
  end

end

app/controllers/vds_controller.rb
class VdsController < ApplicationController
  before_action :set_vd, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "admin", password: "admin"
 before_filter :restrict_access
  # GET /vds
  # GET /vds.json
  def index
    @vds = Vd.all
  end

  # GET /vds/1
  # GET /vds/1.json
  def show
  end

  # GET /vds/new
  def new
    @vd = Vd.new
  end

  # GET /vds/1/edit
  def edit
  end

  # POST /vds
  # POST /vds.json
  def create
    @vd = Vd.new(vd_params)

    respond_to do |format|
      if @vd.save
        format.html { redirect_to @vd, notice: 'Vd was successfully created.' }
        format.json { render :show, status: :created, location: @vd }
      else
        format.html { render :new }
        format.json { render json: @vd.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vds/1
  # PATCH/PUT /vds/1.json
  def update
    respond_to do |format|
      if @vd.update(vd_params)
        format.html { redirect_to @vd, notice: 'Vd was successfully updated.' }
        format.json { render :show, status: :ok, location: @vd }
      else
        format.html { render :edit }
        format.json { render json: @vd.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vds/1
  # DELETE /vds/1.json
  def destroy
    @vd.destroy
    respond_to do |format|
      format.html { redirect_to vds_url, notice: 'Vd was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vd
      @vd = Vd.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vd_params
      params.require(:vd).permit(:name, :email)
    end

    private
      def restrict_access
        api_key = ApiKey.find_by_access_token(params[:access_token])
        head :unauthorized unless api_key
      end
    end
    

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
 
 #Next methods use the twitter API for different tasks
def create_access_token(oauth_token, oauth_token_secret)
consumer = OAuth::Consumer.new("rH8S66dijW7cYX2veCSS0xtHK",
"MXAnfLXwxR0L4eILQSMjPMHClW081P8OW5fNS2QOSCpncLPn2A",
{ :site => "https://api.twitter.com",
:scheme => :header
})
# create the access token
token_hash = { :oauth_token => oauth_token,
:oauth_token_secret => oauth_token_secret
}
access_token = OAuth::AccessToken.from_hash(consumer, token_hash)
return access_token
end
def twittertrends
if session[:user_id] != nil
access_token = create_access_token("845361426290147329-jbdyALVDSXPI4uVFNgHc1gHmk8KkGNL", "PWhsZSt2897NyWkAxtQyMVkajYz9Ac8KbzjJca0sdIDBN")
# use the access token to get the trends
response = access_token.request(:get,
"https://api.twitter.com/1.1/trends/available.json")
info = JSON.parse(response.body)
render json: info
end
def customtweets
if session[:user_id] != nil
access_token = create_access_token(" 845361426290147329-jbdyALVDSXPI4uVFNgHc1gHmk8KkGNL",
"PWhsZSt2897NyWkAxtQyMVkajYz9Ac8KbzjJca0sdIDBN")
# use the access token to get tweets on programming
response = access_token.request(:get,
"https://api.twitter.com/1.1/search/tweets.json?q=programming")
info = JSON.parse(response.body)
render json: info
end
end
def morecustomtweets
if session[:user_id] != nil
access_token = create_access_token(" 845361426290147329-jbdyALVDSXPI4uVFNgHc1gHmk8KkGNL",
"PWhsZSt2897NyWkAxtQyMVkajYz9Ac8KbzjJca0sdIDBN")
# use the access token to get tweets on programming that have been
# posted until 18 October 2014
response = access_token.request(:get,
"https://api.twitter.com/1.1/search/
tweets.json?q=programming&until=2014-10-18")
info = JSON.parse(response.body)
render json: info
end
end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dependencies_helper.rb
module DependenciesHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/vds_helper.rb
module VdsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/welcomesp_helper.rb
module WelcomespHelper
end

app/views/sales/_form.html.erb
<%= form_for(sale) do |f| %>
  <% if sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/index.html.erb
<style>

</style>

<div id="wrapper">

  <h1>Click to Create a Report</h1>

  <button class="generate-sales-report">
    GENERATE REPORT
  </button>

  <div id="footer-javascripts">
    <script type="text/javascript">
      $("button.generate-sales-report").on("click", function() {
        window.location = "<%= sales_report_url %>"
      })
    </script>
  </div>

</div>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Back', sales_path %>

app/views/sales/report.html.erb
<style>
  .sales-report {
    height: 500px;
  }
</style>

<div id="wrapper">

  <h1>THIS IS THE SALES REPORT</h1>

  <%= image_tag "sales-report.png", class: "sales-report" %>

  <div id="footer-javascripts">
    <script type="text/javascript">
    </script>
  </div>

</div>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>

app/views/vds/_form.html.erb
<%= form_for(vd) do |f| %>
  <% if vd.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vd.errors.count, "error") %> prohibited this vd from being saved:</h2>

      <ul>
      <% vd.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vds/edit.html.erb
<h1>Editing Vd</h1>

<%= render 'form', vd: @vd %>

<%= link_to 'Show', @vd %> |
<%= link_to 'Back', vds_path %>

app/views/vds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vds.each do |vd| %>
      <tr>
        <td><%= vd.name %></td>
        <td><%= vd.email %></td>
        <td><%= link_to 'Show', vd %></td>
        <td><%= link_to 'Edit', edit_vd_path(vd) %></td>
        <td><%= link_to 'Destroy', vd, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vd', new_vd_path %>

app/views/vds/new.html.erb
<h1>New Vd</h1>

<%= render 'form', vd: @vd %>

<%= link_to 'Back', vds_path %>

app/views/vds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vd.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @vd.email %>
</p>

<%= link_to 'Edit', edit_vd_path(@vd) %> |
<%= link_to 'Back', vds_path %>