config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  get "/sales" => "sales#index", as: "sales_index"
  get "/sales/report" => "sales#report", as: "sales_report"

  resources :sales



  resources :vds
  resources :products



  get 'info/infogem'

  get 'info/infoauthor'

  get 'info/infolatestgems'

  get 'welcomesp/index'

  resources :dependencies
  get 'sessions/create'

  get 'welcome/index'

  resources :locations


  #root 'welcome#index'

#shuaib api
  #root 'welcomesp#index'
  match 'searchgem', to: 'info#infogem', via: [:get, :post]



  #viak product
  resources :products

  root 'products#index'

  mount Products::ProductsAPI => '/api/products'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
match 'auth/failure', to:  redirect("/") , via: [:get, :post]
match 'signout', to: 'sessions#signout', via: [:get, :post]
match 'twittertrends', to: 'welcome#twittertrends', via: [:get, :post]
match 'customtweets', to: 'welcome#customtweets', via: [:get]
match 'morecustomtweets', to: 'welcome#morecustomtweets', via: [:get]
end

app/models/api_key.rb
class ApiKey < ApplicationRecord
	before_create :generate_access_token

private 
	def generate_access_token
		begin
			self.access_token = SecureRandom.hex
		end while self.class.exists?(access_token: access_token)
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dependency.rb
class Dependency < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
	geocoded_by :address      
  after_validation :geocode  
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, presence: true
  validates :price, presence: true
  validates :short_description, presence: true
end

app/models/rubygemsorg.rb
class RubyGemsOrg
include HTTParty
# GET - /api/v1/gems/[GEM NAME].(json|xml|yaml)
def self.getGemInfo(name)
url="https://rubygems.org/api/v1/gems/#{name}.json"
response = HTTParty.get(url)
responsebody = JSON.parse(response.body)
return responsebody
end
# GET - /api/v1/owners/[USER HANDLE]/gems.(json|xml|yaml)
def self.getGemsOfAuthor(name)
url="https://rubygems.org/api/v1/owners/#{name}/gems.json"
response = HTTParty.get(url)
responsebody = JSON.parse(response.body)
return responsebody
end

end

app/models/sale.rb
class Sale < ApplicationRecord
end

app/models/user.rb
class User < ActiveRecord::Base
def self.create_from_omniauth(auth)
create! do |user|
user.provider = auth["provider"]
user.userid = auth["uid"]
user.name = auth["info"]["nickname"]
end
end
end

app/models/vd.rb
class Vd < ApplicationRecord
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
require 'rubygemsorg'

  def infogem
  	if params[:search_gem].to_s.present?
name = params[:search_gem]
response = RubyGemsOrg.getGemInfo(name)
name = response['name']
@dependency = Dependency.find_by(:name => name)
if @dependency.blank?
@dependency = Dependency.create(:name=>response['name'],
:authors=>response['authors'],:version=>response['version'])
end
else
redirect_to(root_url)
end
end

  

  def infoauthor
  	if params[:search_author].to_s.present?
@author= params[:search_author]
@response = RubyGemsOrg.getGemsOfAuthor(@author)
else
redirect_to(root_url)
end
end


  def infolatestgems
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	def index
    if params[:search].present?
      @locations = Location.near(params[:search], 50, :order => :distance)
    else
      @locations = Location.all
    end
  end

  def show
    @location = Location.find(params[:id])
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(allowed_params)
    if @location.save
      redirect_to @location, :notice => "Successfully created location."
    else
      render :new
    end
  end

  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
    if @location.update_attributes(allowed_params)
      redirect_to @location, :notice  => "Successfully updated location."
    else
      render :edit
    end
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    redirect_to locations_url, :notice => "Successfully destroyed location."
  end

  private

  def allowed_params
    params.require(:location).permit(:id, :address, :latitude, :longitude)
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

  def index
  end

  def report
    ReportWorker.perform_async("07-01-2016", "08-01-2016")
    render text: "REQUEST ADDED TO QUEUE"
  end

  private
  def generate_report
    sleep 30
  end

end

app/controllers/vds_controller.rb
class VdsController < ApplicationController
  before_action :set_vd, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "admin", password: "admin"
 before_filter :restrict_access
  # GET /vds
  # GET /vds.json
  def index
    @vds = Vd.all
  end

  # GET /vds/1
  # GET /vds/1.json
  def show
  end

  # GET /vds/new
  def new
    @vd = Vd.new
  end

  # GET /vds/1/edit
  def edit
  end

  # POST /vds
  # POST /vds.json
  def create
    @vd = Vd.new(vd_params)

    respond_to do |format|
      if @vd.save
        format.html { redirect_to @vd, notice: 'Vd was successfully created.' }
        format.json { render :show, status: :created, location: @vd }
      else
        format.html { render :new }
        format.json { render json: @vd.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vds/1
  # PATCH/PUT /vds/1.json
  def update
    respond_to do |format|
      if @vd.update(vd_params)
        format.html { redirect_to @vd, notice: 'Vd was successfully updated.' }
        format.json { render :show, status: :ok, location: @vd }
      else
        format.html { render :edit }
        format.json { render json: @vd.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vds/1
  # DELETE /vds/1.json
  def destroy
    @vd.destroy
    respond_to do |format|
      format.html { redirect_to vds_url, notice: 'Vd was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vd
      @vd = Vd.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vd_params
      params.require(:vd).permit(:name, :email)
    end

    private
      def restrict_access
        api_key = ApiKey.find_by_access_token(params[:access_token])
        head :unauthorized unless api_key
      end
    end
    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dependencies_helper.rb
module DependenciesHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/vds_helper.rb
module VdsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/welcomesp_helper.rb
module WelcomespHelper
end

app/views/locations/_form.html.erb
<%= form_for @location do |f| %>
  <p>
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </p>
  <p>
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/locations/edit.html.erb
<%= render 'form' %>
<p>
  <%= link_to "Show", @location %> |
  <%= link_to "View All", locations_path %>
</p>

app/views/locations/index.html.erb
<%= form_tag locations_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Near", :name => nil %>
  </p>
<% end %>

<table>
  <tr>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longitude</th>
  </tr>
  <% for location in @locations %>
    <tr>
      <td><%= location.address %></td>
      <td><%= location.latitude %></td>
      <td><%= location.longitude %></td>
      <td><%= link_to "Show", location %></td>
      <td><%= link_to "Edit", edit_location_path(location) %></td>
      <td><%= link_to "Destroy", location, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Location", new_location_path %></p>

app/views/locations/new.html.erb
<%= render 'form' %>
<p><%= link_to "Back to List", locations_path %></p>

app/views/locations/show.html.erb
<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>
<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>
<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" %>

<h3>Nearby locations</h3>
<ul>
<% for location in @location.nearbys(10) %>
  <li><%= link_to location.address, location %> (<%= location.distance.round(2) %> miles)</li>
<% end %>
</ul>

<p>
  <%= link_to "Edit", edit_location_path(@location) %> |
  <%= link_to "Destroy", @location, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", locations_path %>
</p>